<?php
	class cauldron_email extends \Banshee\Protocol\email {
		protected $content_type = "text/html";
		private $footers = array();

		/* Constructor
		 *
		 * INPUT:  string subject[, string e-mail][, string name]
		 * OUTPUT: -
		 * ERROR:  -
		 */
		public function __construct($subject, $from_address = null, $from_name = null, $unsigned = true) {
			$this->add_footer('<a href="https://www.cauldron-vtt.net/">Cauldron VTT website</a>');
			$this->add_footer('<a href="https://www.reddit.com/r/CauldronVTT/">Join on Reddit</a>');
			$this->add_footer('<a href="https://discord.gg/w8FB93taYJ">Join on Discord</a>');

			if ($from_name == null) {
				$from_name = "Cauldron VTT";
			}

			if ($unsigned) {
				$this->add_footer("This email was automatically generated by Cauldron VTT and is therefore unsigned.");
			}

			parent::__construct($subject, $from_address, $from_name);
		}

		/* Add e-mail footer
		 *
		 * INPUT:  string footer
		 * OUTPUT: -
		 * ERROR:  -
		 */
		public function add_footer($str) {
			array_push($this->footers, $str);
		}

		public function set_message_fields($data = null) {
			parent::set_message_fields($data);

			$footer = implode("<span style=\"margin:0 10px\">|</span>", $this->footers);
			$cid = $this->add_image("images/cauldron.png");

			$data = array(
				"FOOTER" => $footer,
				"LOGO"   => $cid);
			foreach ($data as $key => $value) {
				$key = sprintf($this->field_format, $key);
				$this->message_fields[$key] = $value;
			}
		}

		/* Set newsletter content
		 *
		 * INPUT:  string content
		 * OUTPUT: -
		 * ERROR:  -
		 */
		public function message($content) {
			$message = file_get_contents("../extra/cauldron_email.txt");
			$message = str_replace("[MESSAGE]", $content, $message);

			parent::message($message);
		}
	}
?>
